import { Resend } from 'resend';

interface EmailConfig {
  to: string;
  subject: string;
  businessName?: string;
  businessType?: string;
  riskScore: number;
  analysis: string;
}

interface EmailResult {
  success: boolean;
  error?: string;
}

export async function sendEmail(config: EmailConfig): Promise<EmailResult> {
  try {
    const resend = new Resend(process.env.RESEND_API_KEY);

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${config.subject}</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
            h1 { color: #2563eb; margin-bottom: 20px; }
            h2 { color: #1e40af; margin-top: 30px; }
            .risk-score { font-size: 24px; font-weight: bold; color: ${config.riskScore > 70 ? '#059669' : config.riskScore > 40 ? '#d97706' : '#dc2626'}; }
            .section { margin: 20px 0; padding: 20px; background: #f8fafc; border-radius: 8px; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 14px; color: #64748b; }
          </style>
        </head>
        <body>
          <h1>SmartRisk Analysis Report</h1>
          
          <div class="section">
            <h2>Business Overview</h2>
            <p><strong>Business Name:</strong> ${config.businessName || 'N/A'}</p>
            <p><strong>Business Type:</strong> ${config.businessType || 'N/A'}</p>
            <p><strong>Risk Score:</strong> <span class="risk-score">${config.riskScore}/100</span></p>
          </div>

          <div class="section">
            <h2>Analysis Details</h2>
            ${config.analysis.split('\n').map(line => `<p>${line}</p>`).join('')}
          </div>

          <div class="footer">
            <p>This report was generated by SmartRisk. For any questions, please contact our support team.</p>
          </div>
        </body>
      </html>
    `;

    const { data, error } = await resend.emails.send({
      from: 'SmartRisk <no-reply@smartrisk.co.il>',
      to: config.to,
      subject: config.subject,
      html: html
    });

    if (error) {
      console.error('Error sending email:', error);
      return { success: false, error: error.message };
    }

    return { success: true };
  } catch (error) {
    console.error('Error in sendEmail:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to send email'
    };
  }
} 